# Yarn Configuration for AI Coding Assistant

# Package registry
npmRegistryServer: "https://registry.npmjs.org/"

# Save exact version
saveExact: true

# Package lock
enableGlobalCache: true
enableScripts: true

# Security
enableStrictSsl: true
enableTelemetry: false

# Workspaces
enableWorkspaces: true

# Package manager
packageExtensions:
  "*@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"

# Cache
cacheFolder: ".yarn/cache"

# Plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

# Node linker
nodeLinker: node-modules

# PnP
pnpMode: loose

# Zero installs
enableGlobalCache: true