version: '3.8'

services:
  ai-coding-assistant:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./projects:/app/projects
      - ./versions:/app/versions
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ai-network

volumes:
  redis-data:

networks:
  ai-network:
    driver: bridge